apiVersion: v1
kind: Pod
metadata:
  name: cicd-agent
  namespace: jenkins
  labels:
    name: cicd-agent
spec:
  serviceAccount: cap-jenkins-agent
  containers:
  - name: cicd
    image: 023033564114.dkr.ecr.eu-west-1.amazonaws.com/cap-eks-jenkins-ecr-cicd-dev:latest
    command:
    - cat
    resources:
      requests:
        memory: "1024Mi"
        cpu: "500m"
      limits:
        memory: "2048Mi" # Max is half the total available vCpu on m5? large
        cpu: "1000m" # Max is half the total available vCpu on m5? large
    tty: true